openapi: 3.0.3
info:
  title: ACME Games Service
  version: 0.1.0

paths:
  /api/v1/auth:
    post:
      summary: Authenticate using basic authentication
      tags:
        - Authentication
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: "Authorization ticket. The header value is in format: Basic <Base64(email:password)>"
      responses:
        "401":
          description: Authentication failed
        "200":
          description: Authentication succeeded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"

  /api/v1/users/me/games:
    get:
      summary: Gets the current user's games
      tags:
        - Games
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: "Authorization ticket. The header value is in format: Bearer <jwt-token>"
      responses:
        "401":
          description: The user is not authorized to make this request
        "200":
          description: An array containing the authenticated user's games
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Game"


components:
  schemas:
    AuthResponse:
      type: object
      properties:
        ticket:
          type: string
          description: A JWT containing the authenticated user as its payload

    Game:
      type: object
      properties:
        ageRestriction:
          type: number
          description: Indicates if the game is age restricted.
          nullable: true
        gameId:
          type: number
        name:
          type: string
        thumbnail:
          type: string
          description: A URL to a thumbnail image of the game's box art.
